# .air.toml
# Air configuration file

[build]
# Watch for changes in files with the following extensions
include_ext = ["go", "tpl", "html", "css"]

# Exclude watching certain files/folders
exclude_dir = ["tmp", "vendor"]

exclude_file = ["cmd/client.go"]

# The Go build command
cmd = "go build -o ./tmp/main ./cmd/main.go"

[log]
# Log level settings
level = ""

[serve]
# Command to execute after build
cmd = "./tmp/main"
