version: "3"

tasks:

  db: docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d -p 3306:3306 mysql:latest
  mongo: docker run --name mongo -d -p 27017:27017 
           -e MONGO_INITDB_ROOT_USERNAME=visionai
            -e MONGO_INITDB_ROOT_PASSWORD=visionai
               -e MONGO_INITDB_DATABASE=visionai 
                  mongo

  proto: protoc --go_out=. --go-grpc_out=. 
    --go_opt=paths=source_relative 
    proto/fvm_manager/fvm_manager.proto

  dev:
    env:
      MODE: dev
      SERVER_PORT: 8000

      DB_ADDR: root:root@tcp(127.0.0.1:3306)/rtb?charset=utf8mb4&parseTime=True&loc=Local
    cmds:
      - air --build.cmd "go build -o ./tmp/main ./server/cmd/main.go" --build.bin "tmp/main"

  cli:
    cmds:
      - go build -a -v -o cmd/cli/cli cmd/cli/main.go