// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apple_account_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppleAccountTokenByToken = `-- name: GetAppleAccountTokenByToken :one
SELECT id, user_id, token, created_at, updated_at
FROM apple_account_tokens
WHERE token = $1
`

func (q *Queries) GetAppleAccountTokenByToken(ctx context.Context, token pgtype.UUID) (AppleAccountToken, error) {
	row := q.db.QueryRow(ctx, getAppleAccountTokenByToken, token)
	var i AppleAccountToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppleAccountTokenByUser = `-- name: GetAppleAccountTokenByUser :one
SELECT id, user_id, token, created_at, updated_at
FROM apple_account_tokens
WHERE user_id = $1
`

func (q *Queries) GetAppleAccountTokenByUser(ctx context.Context, userID int64) (AppleAccountToken, error) {
	row := q.db.QueryRow(ctx, getAppleAccountTokenByUser, userID)
	var i AppleAccountToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppleAccountToken = `-- name: InsertAppleAccountToken :one
INSERT INTO apple_account_tokens (
    user_id,
    token
) VALUES (
    $1,
    $2
)
RETURNING id, user_id, token, created_at, updated_at
`

type InsertAppleAccountTokenParams struct {
	UserID int64
	Token  pgtype.UUID
}

func (q *Queries) InsertAppleAccountToken(ctx context.Context, arg InsertAppleAccountTokenParams) (AppleAccountToken, error) {
	row := q.db.QueryRow(ctx, insertAppleAccountToken, arg.UserID, arg.Token)
	var i AppleAccountToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
