// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apple_subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByOriginalTx = `-- name: GetSubscriptionByOriginalTx :one
SELECT id, user_id, app_account_token, environment, original_transaction_id, last_transaction_id, web_order_line_item_id, plan_id, provider_product_id, subscription_group_id, level, status, auto_renew_status, current_period_start, current_period_end, grace_period_expires_at, last_event_at, last_notification_created_at, last_payload_hash, last_transaction_snapshot, created_at, updated_at
FROM apple_subscriptions
WHERE original_transaction_id = $1
  AND environment = $2
`

type GetSubscriptionByOriginalTxParams struct {
	OriginalTransactionID string
	Environment           string
}

func (q *Queries) GetSubscriptionByOriginalTx(ctx context.Context, arg GetSubscriptionByOriginalTxParams) (AppleSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOriginalTx, arg.OriginalTransactionID, arg.Environment)
	var i AppleSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppAccountToken,
		&i.Environment,
		&i.OriginalTransactionID,
		&i.LastTransactionID,
		&i.WebOrderLineItemID,
		&i.PlanID,
		&i.ProviderProductID,
		&i.SubscriptionGroupID,
		&i.Level,
		&i.Status,
		&i.AutoRenewStatus,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.GracePeriodExpiresAt,
		&i.LastEventAt,
		&i.LastNotificationCreatedAt,
		&i.LastPayloadHash,
		&i.LastTransactionSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsForUserEntitlement = `-- name: ListSubscriptionsForUserEntitlement :many
SELECT id, user_id, app_account_token, environment, original_transaction_id, last_transaction_id, web_order_line_item_id, plan_id, provider_product_id, subscription_group_id, level, status, auto_renew_status, current_period_start, current_period_end, grace_period_expires_at, last_event_at, last_notification_created_at, last_payload_hash, last_transaction_snapshot, created_at, updated_at
FROM apple_subscriptions
WHERE user_id = $1
  AND environment = ANY($2::text[])
ORDER BY
    CASE WHEN status IN ('ACTIVE', 'CANCELED')
              AND COALESCE(grace_period_expires_at, current_period_end) > now()
         THEN 0 ELSE 1 END,
    level DESC,
    COALESCE(grace_period_expires_at, current_period_end) DESC,
    last_event_at DESC
`

type ListSubscriptionsForUserEntitlementParams struct {
	UserID  int64
	Column2 []string
}

func (q *Queries) ListSubscriptionsForUserEntitlement(ctx context.Context, arg ListSubscriptionsForUserEntitlementParams) ([]AppleSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUserEntitlement, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppleSubscription
	for rows.Next() {
		var i AppleSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppAccountToken,
			&i.Environment,
			&i.OriginalTransactionID,
			&i.LastTransactionID,
			&i.WebOrderLineItemID,
			&i.PlanID,
			&i.ProviderProductID,
			&i.SubscriptionGroupID,
			&i.Level,
			&i.Status,
			&i.AutoRenewStatus,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.GracePeriodExpiresAt,
			&i.LastEventAt,
			&i.LastNotificationCreatedAt,
			&i.LastPayloadHash,
			&i.LastTransactionSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO apple_subscriptions (
    user_id,
    app_account_token,
    environment,
    original_transaction_id,
    last_transaction_id,
    web_order_line_item_id,
    plan_id,
    provider_product_id,
    subscription_group_id,
    level,
    status,
    auto_renew_status,
    current_period_start,
    current_period_end,
    grace_period_expires_at,
    last_event_at,
    last_notification_created_at,
    last_payload_hash,
    last_transaction_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (original_transaction_id, environment) DO UPDATE SET
    last_transaction_id          = EXCLUDED.last_transaction_id,
    web_order_line_item_id       = EXCLUDED.web_order_line_item_id,
    plan_id                      = EXCLUDED.plan_id,
    provider_product_id          = EXCLUDED.provider_product_id,
    subscription_group_id        = EXCLUDED.subscription_group_id,
    level                        = EXCLUDED.level,
    status                       = EXCLUDED.status,
    auto_renew_status            = EXCLUDED.auto_renew_status,
    current_period_start         = EXCLUDED.current_period_start,
    current_period_end           = EXCLUDED.current_period_end,
    grace_period_expires_at      = EXCLUDED.grace_period_expires_at,
    last_event_at                = EXCLUDED.last_event_at,
    last_notification_created_at = EXCLUDED.last_notification_created_at,
    last_payload_hash            = EXCLUDED.last_payload_hash,
    last_transaction_snapshot    = EXCLUDED.last_transaction_snapshot,
    updated_at                   = now()
RETURNING id, user_id, app_account_token, environment, original_transaction_id, last_transaction_id, web_order_line_item_id, plan_id, provider_product_id, subscription_group_id, level, status, auto_renew_status, current_period_start, current_period_end, grace_period_expires_at, last_event_at, last_notification_created_at, last_payload_hash, last_transaction_snapshot, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID                    int64
	AppAccountToken           pgtype.UUID
	Environment               string
	OriginalTransactionID     string
	LastTransactionID         string
	WebOrderLineItemID        string
	PlanID                    string
	ProviderProductID         string
	SubscriptionGroupID       string
	Level                     int32
	Status                    string
	AutoRenewStatus           string
	CurrentPeriodStart        pgtype.Timestamptz
	CurrentPeriodEnd          pgtype.Timestamptz
	GracePeriodExpiresAt      pgtype.Timestamptz
	LastEventAt               pgtype.Timestamptz
	LastNotificationCreatedAt pgtype.Timestamptz
	LastPayloadHash           string
	LastTransactionSnapshot   []byte
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (AppleSubscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.AppAccountToken,
		arg.Environment,
		arg.OriginalTransactionID,
		arg.LastTransactionID,
		arg.WebOrderLineItemID,
		arg.PlanID,
		arg.ProviderProductID,
		arg.SubscriptionGroupID,
		arg.Level,
		arg.Status,
		arg.AutoRenewStatus,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.GracePeriodExpiresAt,
		arg.LastEventAt,
		arg.LastNotificationCreatedAt,
		arg.LastPayloadHash,
		arg.LastTransactionSnapshot,
	)
	var i AppleSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppAccountToken,
		&i.Environment,
		&i.OriginalTransactionID,
		&i.LastTransactionID,
		&i.WebOrderLineItemID,
		&i.PlanID,
		&i.ProviderProductID,
		&i.SubscriptionGroupID,
		&i.Level,
		&i.Status,
		&i.AutoRenewStatus,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.GracePeriodExpiresAt,
		&i.LastEventAt,
		&i.LastNotificationCreatedAt,
		&i.LastPayloadHash,
		&i.LastTransactionSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
