// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apple_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppleEventByUUID = `-- name: GetAppleEventByUUID :one
SELECT id, notification_uuid, notification_type, subtype, environment, user_id, app_account_token, original_transaction_id, transaction_id, web_order_line_item_id, processing_status, processing_error, raw_jws_sha256, decoded_payload, notification_created_at, created_at
FROM apple_events
WHERE notification_uuid = $1
`

func (q *Queries) GetAppleEventByUUID(ctx context.Context, notificationUuid string) (AppleEvent, error) {
	row := q.db.QueryRow(ctx, getAppleEventByUUID, notificationUuid)
	var i AppleEvent
	err := row.Scan(
		&i.ID,
		&i.NotificationUuid,
		&i.NotificationType,
		&i.Subtype,
		&i.Environment,
		&i.UserID,
		&i.AppAccountToken,
		&i.OriginalTransactionID,
		&i.TransactionID,
		&i.WebOrderLineItemID,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.RawJwsSha256,
		&i.DecodedPayload,
		&i.NotificationCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAppleEventIfNotExists = `-- name: InsertAppleEventIfNotExists :one
INSERT INTO apple_events (
    notification_uuid,
    notification_type,
    subtype,
    environment,
    user_id,
    app_account_token,
    original_transaction_id,
    transaction_id,
    web_order_line_item_id,
    processing_status,
    processing_error,
    raw_jws_sha256,
    decoded_payload,
    notification_created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (notification_uuid) DO NOTHING
RETURNING id
`

type InsertAppleEventIfNotExistsParams struct {
	NotificationUuid      string
	NotificationType      string
	Subtype               string
	Environment           string
	UserID                pgtype.Int8
	AppAccountToken       pgtype.UUID
	OriginalTransactionID string
	TransactionID         string
	WebOrderLineItemID    string
	ProcessingStatus      string
	ProcessingError       string
	RawJwsSha256          string
	DecodedPayload        []byte
	NotificationCreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAppleEventIfNotExists(ctx context.Context, arg InsertAppleEventIfNotExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAppleEventIfNotExists,
		arg.NotificationUuid,
		arg.NotificationType,
		arg.Subtype,
		arg.Environment,
		arg.UserID,
		arg.AppAccountToken,
		arg.OriginalTransactionID,
		arg.TransactionID,
		arg.WebOrderLineItemID,
		arg.ProcessingStatus,
		arg.ProcessingError,
		arg.RawJwsSha256,
		arg.DecodedPayload,
		arg.NotificationCreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingAppleEvents = `-- name: ListPendingAppleEvents :many
SELECT id, notification_uuid, notification_type, subtype, environment, user_id, app_account_token, original_transaction_id, transaction_id, web_order_line_item_id, processing_status, processing_error, raw_jws_sha256, decoded_payload, notification_created_at, created_at
FROM apple_events
WHERE processing_status = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingAppleEventsParams struct {
	ProcessingStatus string
	Limit            int32
}

func (q *Queries) ListPendingAppleEvents(ctx context.Context, arg ListPendingAppleEventsParams) ([]AppleEvent, error) {
	rows, err := q.db.Query(ctx, listPendingAppleEvents, arg.ProcessingStatus, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppleEvent
	for rows.Next() {
		var i AppleEvent
		if err := rows.Scan(
			&i.ID,
			&i.NotificationUuid,
			&i.NotificationType,
			&i.Subtype,
			&i.Environment,
			&i.UserID,
			&i.AppAccountToken,
			&i.OriginalTransactionID,
			&i.TransactionID,
			&i.WebOrderLineItemID,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.RawJwsSha256,
			&i.DecodedPayload,
			&i.NotificationCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
