// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppleAccountToken struct {
	ID        int64
	UserID    int64
	Token     pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppleEvent struct {
	ID                    int64
	NotificationUuid      string
	NotificationType      string
	Subtype               string
	Environment           string
	UserID                pgtype.Int8
	AppAccountToken       pgtype.UUID
	OriginalTransactionID string
	TransactionID         string
	WebOrderLineItemID    string
	ProcessingStatus      string
	ProcessingError       string
	RawJwsSha256          string
	DecodedPayload        []byte
	NotificationCreatedAt pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

type AppleSubscription struct {
	ID                        int64
	UserID                    int64
	AppAccountToken           pgtype.UUID
	Environment               string
	OriginalTransactionID     string
	LastTransactionID         string
	WebOrderLineItemID        string
	PlanID                    string
	ProviderProductID         string
	SubscriptionGroupID       string
	Level                     int32
	Status                    string
	AutoRenewStatus           string
	CurrentPeriodStart        pgtype.Timestamptz
	CurrentPeriodEnd          pgtype.Timestamptz
	GracePeriodExpiresAt      pgtype.Timestamptz
	LastEventAt               pgtype.Timestamptz
	LastNotificationCreatedAt pgtype.Timestamptz
	LastPayloadHash           string
	LastTransactionSnapshot   []byte
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type AuthIdentity struct {
	Provider        string
	ProviderSubject string
	UserID          int64
	Email           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
