// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (CreateAuthIdentityRow, error)
	CreateUser(ctx context.Context, name string) (CreateUserRow, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserInfoByAuthIdentity(ctx context.Context, arg GetUserInfoByAuthIdentityParams) (GetUserInfoByAuthIdentityRow, error)
}

var _ Querier = (*Queries)(nil)
