// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (
    provider,
    provider_subject,
    user_id,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING provider, provider_subject, user_id, email
`

type CreateAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
	UserID          int64
	Email           string
}

type CreateAuthIdentityRow struct {
	Provider        string
	ProviderSubject string
	UserID          int64
	Email           string
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (CreateAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.Provider,
		arg.ProviderSubject,
		arg.UserID,
		arg.Email,
	)
	var i CreateAuthIdentityRow
	err := row.Scan(
		&i.Provider,
		&i.ProviderSubject,
		&i.UserID,
		&i.Email,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
VALUES ($1)
RETURNING id, name
`

type CreateUserRow struct {
	ID   int64
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, name string) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserInfoByAuthIdentity = `-- name: GetUserInfoByAuthIdentity :one
SELECT
    u.id,
    ai.email,
    ai.provider,
    ai.provider_subject
FROM auth_identities ai
JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1
  AND ai.provider_subject = $2
`

type GetUserInfoByAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
}

type GetUserInfoByAuthIdentityRow struct {
	ID              int64
	Email           string
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetUserInfoByAuthIdentity(ctx context.Context, arg GetUserInfoByAuthIdentityParams) (GetUserInfoByAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserInfoByAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i GetUserInfoByAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Provider,
		&i.ProviderSubject,
	)
	return i, err
}
